spring.datasource.url=jdbc:h2:mem:batchdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

finance.api.base-url=${FINANCE_API_URL:http://localhost:8080}
finance.api.email=${FINANCE_API_EMAIL:admin@email.com}
finance.api.password=${FINANCE_API_PASSWORD:senha123}